### ISSUE TITLE
Authentication with PassportJS?

### ISSUE THREAD

**Issue by soulwire** [klei/generator-klei#9]
First of all, thanks for this template; I've been using it for a couple of projects and it's really nice.

I was wondering how you would go about adding authentication, probably using [Passport](http://passportjs.org/) since it simplifies the process a lot? The tricky part seems to be maintaining sessions on the client and using that session securely to restrict certain api calls to authenticated users / return specific results for a user.

Any suggestions for getting this working or plans to integrate this?

Thanks!

**Comment by joakimbeng** [comment]
Hi @soulwire , I'm not sure if I follow what your problem is?

You should integrate it as you would with an ordinary `express` app, inside `./src/app.js`. You should also create an authentication middleware to be used in your controller e.g:

`my.controller.js`:

``` javascript
var authMiddleware = require('../auth.js');

// POST /api/my
exports.create = [authMiddleware, function (req, res) {
  ...
}];
```

There's no plan for the moment to have passport integrated by default in this generator, that's up to each user of the generator to decide what security solution they want.

**Comment by soulwire** [comment]
Hey @joakimbeng,

You're right, I can see now it's pretty trivial to add passport and it makes sense to keep it out of the template since it's not a particularly common use case. Sorry to waste your time and thanks again for the great repo.

**Comment by joakimbeng** [comment]
@soulwire no problem at all :)
When I have a nice general though out security setup I'll probably add it as an option in the generator in the future.
